### ISSUE TITLE
Which configuration to produce the best model?

### ISSUE THREAD

**Issue by panovr** [mrsebai/aerial-tile-segmentation#2]
Hi,
when I use the code for training, my configuration is:
- unet wit input 256x256x3
- noScale
- skip4 Residual
- serialCenter
- sgd optimizer
- SparseCategoricalCrossentropy loss

I get the result for validation dataset:
```
Background	Building	Roads	Vegetation	Tree	         Car
0.199138	 0.770326    0.678813	0.652222	0.652314	0.66924
```

However, in your presentation, your best model give the result:
```
Background   Building        Roads	Vegetation	Tree	          Car
0.3132	      0.8701         0.8030	0.6928	        0.7061	       0.8243
```

Which configuration you use to produce the best model? And may you have the best model for downloading?
Thanks!

**Comment by mrsebai** [comment]
Hello Yili
As you can read in README.md I used the following infrastructure:

  *   16-Core, 64GB RAM
  *   Nvidia 16GB GPU (Tesla P100)
  *   VM instance on GCP

This is really a beefy setup and it took up to 6 hours of training on GCP, myself I couldn't afford it, it was charged to my company at that time.
I remember that my best model was obtained using iou_metric as the optimizer (even though I observed some instability because this optimizer doesn't have a nice derivative)
Your results looks honest, did you obtain these results with test time augmentations? You can gain several points of accuracy just this simple trick.
I am no longer active on the project and no longer have the model collaterals, sorry

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Yili Zhao ***@***.***>
Envoyé : Thursday, April 7, 2022 9:49:35 AM
À : mrsebai/aerial-tile-segmentation ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [mrsebai/aerial-tile-segmentation] Which configuration to produce the best model? (Issue #2)


Hi,
when I use the code for training, my configuration is:

  *   unet wit input 256x256x3
  *   noScale
  *   skip4 Residual
  *   serialCenter
  *   sgd optimizer
  *   SparseCategoricalCrossentropy loss

I get the result for validation dataset:

Background      Building        Roads   Vegetation      Tree             Car
0.199138         0.770326    0.678813   0.652222        0.652314        0.66924


However, in your presentation, your best model give the result:

Background   Building        Roads      Vegetation      Tree              Car
0.3132        0.8701         0.8030     0.6928          0.7061         0.8243


Which configuration you use to produce the best model? And may you have the best model for downloading?
Thanks!

**Comment by panovr** [comment]
I will try test time augmentations.
How about One Cycle Policy Training, does it help?

**Comment by mrsebai** [comment]
If you are using sgd I recommend One cycle policy training. If using Adam I don't know, never tried it because I didn't find anything in literature. Adam by itself is good for converging and stability.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Yili Zhao ***@***.***>
Envoyé : Thursday, April 7, 2022 1:53:41 PM
À : mrsebai/aerial-tile-segmentation ***@***.***>
Cc : Maher Sebai ***@***.***>; Comment ***@***.***>
Objet : Re: [mrsebai/aerial-tile-segmentation] Which configuration to produce the best model? (Issue #2)


I will try test time augmentations.
How about One Cycle Policy Training, does it help?
