### ISSUE TITLE
How to combine CE loss with Jaccard loss?

### ISSUE THREAD

**Issue by panovr** [mrsebai/aerial-tile-segmentation#3]
Hi,
  with some experiments, I found that CE loss and Jaccard loss both have their own advantages, and they are used in the code separately. Did you ever consider to combine them? Will this improve IoU score than single CE loss or Jaccard Loss?

**Comment by mrsebai** [comment]
Hello, sorry for the late answer.
I did try various loss function and surprisingly the jaccard loss was the one that brought me the best performin model. I say surprising because jaccard loss doesn't have a nice derivative (it's a quotient) and was afraid of instability. I didn't try to mix loss function I i targeted loss functions one by one based on my papers reading, but everything is possible is deep learning and only experiments results matters. Congratulations if you achieved better results then this notebook :-)

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Yili Zhao ***@***.***>
Envoyé : Sunday, May 29, 2022 7:47:11 AM
À : mrsebai/aerial-tile-segmentation ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [mrsebai/aerial-tile-segmentation] How to combine CE loss with Jaccard loss? (Issue #3)


Hi,
with some experiments, I found that CE loss and Jaccard loss both have their own advantages, and they are used in the code separately. Did you ever consider to combine them? Will this improve IoU score than single CE loss or Jaccard Loss?
